# Generated by Django 3.1.5 on 2023-07-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appwebsite', '0002_auto_20230718_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_file', models.FileField(upload_to='docs/')),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
